id: P010596
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W24121
  title: རྗེ་བླ་མ་འཁྲུལ་ཞིག་བྱང་ཆུབ་གླིང་པའི་རྣམ་ཐར་སྐལ་བཟང་དགའ་བའི་བདུད་རྩིའི་སྤྲིན་ཚོགས
  author: ''
  volumes:
    4c84ca9ad3b446138d241d19ab73ced9:
      image_group_id: I4471
      title: ''
      volume_number: 1
      total_pages: 498
      base_file: v001.txt
