id: IB766DD43
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T06:24:40+00:00'
last_modified: '2022-06-08T16:07:41.552613+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W24121
  title: རྗེ་བླ་མ་འཁྲུལ་ཞིག་བྱང་ཆུབ་གླིང་པའི་རྣམ་ཐར་སྐལ་བཟང་དགའ་བའི་བདུད་རྩིའི་སྤྲིན་ཚོགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    556A:
      image_group_id: I4471
      title: ''
      total_pages: 498
      order: 1
      base_file: 556A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
